### ISSUE TITLE
 failed to load the base model

### ISSUE THREAD

**Issue by philoxmyu** [InstantID/InstantID#35]
StableDiffusionXLInstantIDPipeline failed to load the base model(wangqixun/YamerMIX_v8). The base model has been downloaded locally, but the pipe is NONE after loading. What are the possible reasons? Thanks

**Comment by haofanwang** [comment]
If you have downloaded locally, you should use the local path. How do you load?

**Comment by philoxmyu** [comment]
If use a local path, I will change the path. What’s strange is that whether I download it directly (base_model="wangqixun/YamerMIX_v8") or switch to my local directory path, the pipe is NONE after loading.

Use infer.py directly, the result is normal. I know the reason. Thanks

**Comment by HD-Song** [comment]
I also met the problem, whether use "wangqixun/YamerMIX_v8" or local path, the pip is NONE after loading.

**Comment by HD-Song** [comment]
I also met the problem, whether use "wangqixun/YamerMIX_v8" or local path, the pip is NONE after loading.

**Comment by HD-Song** [comment]
I also met the problem, whether use "wangqixun/YamerMIX_v8" or local path, the pip is NONE after loading.

When using infer.py directly, "StableDiffusionXLControlNetPipeline.check_inputs() takes from 5 to 14 positional arguments but 15 were given", it seems pipeline_stable_diffusion_xl_instantid.py::__call__()::self.check_inputs() got too much args? 

Is it because the diffusers version? Could you please provide your environment list? Thanks!
